// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: access/v1/access.proto

package access

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// https://openid.github.io/authzen/#name-the-access-evaluation-api-r
type EvaluationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *Subject               `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Action        *Action                `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Resource      *Resource              `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationRequest) Reset() {
	*x = EvaluationRequest{}
	mi := &file_access_v1_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationRequest) ProtoMessage() {}

func (x *EvaluationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_access_v1_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationRequest.ProtoReflect.Descriptor instead.
func (*EvaluationRequest) Descriptor() ([]byte, []int) {
	return file_access_v1_access_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluationRequest) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *EvaluationRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *EvaluationRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *EvaluationRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

// https://openid.github.io/authzen/#name-the-access-evaluation-api-re
type EvaluationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      bool                   `protobuf:"varint,1,opt,name=decision,proto3" json:"decision,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationResponse) Reset() {
	*x = EvaluationResponse{}
	mi := &file_access_v1_access_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationResponse) ProtoMessage() {}

func (x *EvaluationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_access_v1_access_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationResponse.ProtoReflect.Descriptor instead.
func (*EvaluationResponse) Descriptor() ([]byte, []int) {
	return file_access_v1_access_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluationResponse) GetDecision() bool {
	if x != nil {
		return x.Decision
	}
	return false
}

func (x *EvaluationResponse) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

// https://openid.github.io/authzen/#name-the-access-evaluations-api-
type EvaluationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *Subject               `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Action        *Action                `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Resource      *Resource              `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	Evaluations   []*EvaluationRequest   `protobuf:"bytes,5,rep,name=evaluations,proto3" json:"evaluations,omitempty"`
	Options       *structpb.Struct       `protobuf:"bytes,6,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationsRequest) Reset() {
	*x = EvaluationsRequest{}
	mi := &file_access_v1_access_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationsRequest) ProtoMessage() {}

func (x *EvaluationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_access_v1_access_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationsRequest.ProtoReflect.Descriptor instead.
func (*EvaluationsRequest) Descriptor() ([]byte, []int) {
	return file_access_v1_access_proto_rawDescGZIP(), []int{2}
}

func (x *EvaluationsRequest) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *EvaluationsRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *EvaluationsRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *EvaluationsRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *EvaluationsRequest) GetEvaluations() []*EvaluationRequest {
	if x != nil {
		return x.Evaluations
	}
	return nil
}

func (x *EvaluationsRequest) GetOptions() *structpb.Struct {
	if x != nil {
		return x.Options
	}
	return nil
}

// https://openid.github.io/authzen/#name-access-evaluations-api-resp
type EvaluationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Evaluations   []*EvaluationResponse  `protobuf:"bytes,1,rep,name=evaluations,proto3" json:"evaluations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationsResponse) Reset() {
	*x = EvaluationsResponse{}
	mi := &file_access_v1_access_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationsResponse) ProtoMessage() {}

func (x *EvaluationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_access_v1_access_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationsResponse.ProtoReflect.Descriptor instead.
func (*EvaluationsResponse) Descriptor() ([]byte, []int) {
	return file_access_v1_access_proto_rawDescGZIP(), []int{3}
}

func (x *EvaluationsResponse) GetEvaluations() []*EvaluationResponse {
	if x != nil {
		return x.Evaluations
	}
	return nil
}

// https://openid.github.io/authzen/#name-the-subject-search-api-requ
type SubjectSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *Subject               `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Action        *Action                `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Resource      *Resource              `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	Page          *Page                  `protobuf:"bytes,5,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectSearchRequest) Reset() {
	*x = SubjectSearchRequest{}
	mi := &file_access_v1_access_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectSearchRequest) ProtoMessage() {}

func (x *SubjectSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_access_v1_access_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectSearchRequest.ProtoReflect.Descriptor instead.
func (*SubjectSearchRequest) Descriptor() ([]byte, []int) {
	return file_access_v1_access_proto_rawDescGZIP(), []int{4}
}

func (x *SubjectSearchRequest) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *SubjectSearchRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *SubjectSearchRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *SubjectSearchRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SubjectSearchRequest) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

// https://openid.github.io/authzen/#name-the-subject-search-api-resp
type SubjectSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Subject             `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Page          *Page                  `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectSearchResponse) Reset() {
	*x = SubjectSearchResponse{}
	mi := &file_access_v1_access_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectSearchResponse) ProtoMessage() {}

func (x *SubjectSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_access_v1_access_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectSearchResponse.ProtoReflect.Descriptor instead.
func (*SubjectSearchResponse) Descriptor() ([]byte, []int) {
	return file_access_v1_access_proto_rawDescGZIP(), []int{5}
}

func (x *SubjectSearchResponse) GetResults() []*Subject {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SubjectSearchResponse) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

// https://openid.github.io/authzen/#name-the-resource-search-api-req
type ResourceSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *Subject               `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Action        *Action                `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Resource      *Resource              `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	Page          *Page                  `protobuf:"bytes,5,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSearchRequest) Reset() {
	*x = ResourceSearchRequest{}
	mi := &file_access_v1_access_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSearchRequest) ProtoMessage() {}

func (x *ResourceSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_access_v1_access_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSearchRequest.ProtoReflect.Descriptor instead.
func (*ResourceSearchRequest) Descriptor() ([]byte, []int) {
	return file_access_v1_access_proto_rawDescGZIP(), []int{6}
}

func (x *ResourceSearchRequest) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *ResourceSearchRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ResourceSearchRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ResourceSearchRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ResourceSearchRequest) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

// https://openid.github.io/authzen/#name-the-resource-search-api-res
type ResourceSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Resource            `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Page          *Page                  `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSearchResponse) Reset() {
	*x = ResourceSearchResponse{}
	mi := &file_access_v1_access_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSearchResponse) ProtoMessage() {}

func (x *ResourceSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_access_v1_access_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSearchResponse.ProtoReflect.Descriptor instead.
func (*ResourceSearchResponse) Descriptor() ([]byte, []int) {
	return file_access_v1_access_proto_rawDescGZIP(), []int{7}
}

func (x *ResourceSearchResponse) GetResults() []*Resource {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ResourceSearchResponse) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

// https://openid.github.io/authzen/#name-the-action-search-api-reque
type ActionSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *Subject               `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Action        *Action                `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Resource      *Resource              `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	Page          *Page                  `protobuf:"bytes,5,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionSearchRequest) Reset() {
	*x = ActionSearchRequest{}
	mi := &file_access_v1_access_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSearchRequest) ProtoMessage() {}

func (x *ActionSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_access_v1_access_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSearchRequest.ProtoReflect.Descriptor instead.
func (*ActionSearchRequest) Descriptor() ([]byte, []int) {
	return file_access_v1_access_proto_rawDescGZIP(), []int{8}
}

func (x *ActionSearchRequest) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *ActionSearchRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ActionSearchRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ActionSearchRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ActionSearchRequest) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

// https://openid.github.io/authzen/#name-the-action-search-api-respo
type ActionSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Action              `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Page          *Page                  `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionSearchResponse) Reset() {
	*x = ActionSearchResponse{}
	mi := &file_access_v1_access_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSearchResponse) ProtoMessage() {}

func (x *ActionSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_access_v1_access_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSearchResponse.ProtoReflect.Descriptor instead.
func (*ActionSearchResponse) Descriptor() ([]byte, []int) {
	return file_access_v1_access_proto_rawDescGZIP(), []int{9}
}

func (x *ActionSearchResponse) GetResults() []*Action {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ActionSearchResponse) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

// https://openid.github.io/authzen/#name-subject
type Subject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,3,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subject) Reset() {
	*x = Subject{}
	mi := &file_access_v1_access_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_access_v1_access_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_access_v1_access_proto_rawDescGZIP(), []int{10}
}

func (x *Subject) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Subject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subject) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

// https://openid.github.io/authzen/#name-action
type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_access_v1_access_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_access_v1_access_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_access_v1_access_proto_rawDescGZIP(), []int{11}
}

func (x *Action) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Action) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

// https://openid.github.io/authzen/#name-resource
type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,3,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_access_v1_access_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_access_v1_access_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_access_v1_access_proto_rawDescGZIP(), []int{12}
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextToken     string                 `protobuf:"bytes,1,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_access_v1_access_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_access_v1_access_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_access_v1_access_proto_rawDescGZIP(), []int{13}
}

func (x *Page) GetNextToken() string {
	if x != nil {
		return x.NextToken
	}
	return ""
}

var File_access_v1_access_proto protoreflect.FileDescriptor

const file_access_v1_access_proto_rawDesc = "" +
	"\n" +
	"\x16access/v1/access.proto\x12\x11authzen.access.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xe8\x01\n" +
	"\x11EvaluationRequest\x124\n" +
	"\asubject\x18\x01 \x01(\v2\x1a.authzen.access.v1.SubjectR\asubject\x121\n" +
	"\x06action\x18\x02 \x01(\v2\x19.authzen.access.v1.ActionR\x06action\x127\n" +
	"\bresource\x18\x03 \x01(\v2\x1b.authzen.access.v1.ResourceR\bresource\x121\n" +
	"\acontext\x18\x04 \x01(\v2\x17.google.protobuf.StructR\acontext\"c\n" +
	"\x12EvaluationResponse\x12\x1a\n" +
	"\bdecision\x18\x01 \x01(\bR\bdecision\x121\n" +
	"\acontext\x18\x02 \x01(\v2\x17.google.protobuf.StructR\acontext\"\xe4\x02\n" +
	"\x12EvaluationsRequest\x124\n" +
	"\asubject\x18\x01 \x01(\v2\x1a.authzen.access.v1.SubjectR\asubject\x121\n" +
	"\x06action\x18\x02 \x01(\v2\x19.authzen.access.v1.ActionR\x06action\x127\n" +
	"\bresource\x18\x03 \x01(\v2\x1b.authzen.access.v1.ResourceR\bresource\x121\n" +
	"\acontext\x18\x04 \x01(\v2\x17.google.protobuf.StructR\acontext\x12F\n" +
	"\vevaluations\x18\x05 \x03(\v2$.authzen.access.v1.EvaluationRequestR\vevaluations\x121\n" +
	"\aoptions\x18\x06 \x01(\v2\x17.google.protobuf.StructR\aoptions\"^\n" +
	"\x13EvaluationsResponse\x12G\n" +
	"\vevaluations\x18\x01 \x03(\v2%.authzen.access.v1.EvaluationResponseR\vevaluations\"\x98\x02\n" +
	"\x14SubjectSearchRequest\x124\n" +
	"\asubject\x18\x01 \x01(\v2\x1a.authzen.access.v1.SubjectR\asubject\x121\n" +
	"\x06action\x18\x02 \x01(\v2\x19.authzen.access.v1.ActionR\x06action\x127\n" +
	"\bresource\x18\x03 \x01(\v2\x1b.authzen.access.v1.ResourceR\bresource\x121\n" +
	"\acontext\x18\x04 \x01(\v2\x17.google.protobuf.StructR\acontext\x12+\n" +
	"\x04page\x18\x05 \x01(\v2\x17.authzen.access.v1.PageR\x04page\"z\n" +
	"\x15SubjectSearchResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.authzen.access.v1.SubjectR\aresults\x12+\n" +
	"\x04page\x18\x02 \x01(\v2\x17.authzen.access.v1.PageR\x04page\"\x99\x02\n" +
	"\x15ResourceSearchRequest\x124\n" +
	"\asubject\x18\x01 \x01(\v2\x1a.authzen.access.v1.SubjectR\asubject\x121\n" +
	"\x06action\x18\x02 \x01(\v2\x19.authzen.access.v1.ActionR\x06action\x127\n" +
	"\bresource\x18\x03 \x01(\v2\x1b.authzen.access.v1.ResourceR\bresource\x121\n" +
	"\acontext\x18\x04 \x01(\v2\x17.google.protobuf.StructR\acontext\x12+\n" +
	"\x04page\x18\x05 \x01(\v2\x17.authzen.access.v1.PageR\x04page\"|\n" +
	"\x16ResourceSearchResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.authzen.access.v1.ResourceR\aresults\x12+\n" +
	"\x04page\x18\x02 \x01(\v2\x17.authzen.access.v1.PageR\x04page\"\x97\x02\n" +
	"\x13ActionSearchRequest\x124\n" +
	"\asubject\x18\x01 \x01(\v2\x1a.authzen.access.v1.SubjectR\asubject\x121\n" +
	"\x06action\x18\x02 \x01(\v2\x19.authzen.access.v1.ActionR\x06action\x127\n" +
	"\bresource\x18\x03 \x01(\v2\x1b.authzen.access.v1.ResourceR\bresource\x121\n" +
	"\acontext\x18\x04 \x01(\v2\x17.google.protobuf.StructR\acontext\x12+\n" +
	"\x04page\x18\x05 \x01(\v2\x17.authzen.access.v1.PageR\x04page\"x\n" +
	"\x14ActionSearchResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.authzen.access.v1.ActionR\aresults\x12+\n" +
	"\x04page\x18\x02 \x01(\v2\x17.authzen.access.v1.PageR\x04page\"f\n" +
	"\aSubject\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x127\n" +
	"\n" +
	"properties\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\"U\n" +
	"\x06Action\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\n" +
	"properties\x18\x02 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\"g\n" +
	"\bResource\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x127\n" +
	"\n" +
	"properties\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\"%\n" +
	"\x04Page\x12\x1d\n" +
	"\n" +
	"next_token\x18\x01 \x01(\tR\tnextToken2\xc3\b\n" +
	"\x06Access\x12\xcd\x01\n" +
	"\n" +
	"Evaluation\x12$.authzen.access.v1.EvaluationRequest\x1a%.authzen.access.v1.EvaluationResponse\"r\x92AO\n" +
	"\aauthzen\x12\x15Access Evaluation API\x1a\x03TBD*(openid.authzen.access.v1.evaluation.post\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/access/v1/evaluation\x12\xd4\x01\n" +
	"\vEvaluations\x12%.authzen.access.v1.EvaluationsRequest\x1a&.authzen.access.v1.EvaluationsResponse\"v\x92AR\n" +
	"\aauthzen\x12\x16Access Evaluations API\x1a\x04TBD.*)openid.authzen.access.v1.evaluations.post\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/access/v1/evaluations\x12\xdc\x01\n" +
	"\rSubjectSearch\x12'.authzen.access.v1.SubjectSearchRequest\x1a(.authzen.access.v1.SubjectSearchResponse\"x\x92AQ\n" +
	"\aauthzen\x12\x12Subject Search API\x1a\x04TBD.*,openid.authzen.access.v1.search.subject.post\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/access/v1/search/subject\x12\xd9\x01\n" +
	"\x0eResourceSearch\x12(.authzen.access.v1.ResourceSearchRequest\x1a).authzen.access.v1.ResourceSearchResponse\"r\x92AJ\n" +
	"\aauthzen\x12\x13Resource Search API\x1a\x04TBD.*$openid.authzen.access.v1.search.post\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/access/v1/search/resource\x12\xd6\x01\n" +
	"\fActionSearch\x12&.authzen.access.v1.ActionSearchRequest\x1a'.authzen.access.v1.ActionSearchResponse\"u\x92AO\n" +
	"\aauthzen\x12\x11Action Search API\x1a\x04TBD.*+openid.authzen.access.v1.search.action.post\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/access/v1/search/actionB\xb5\x03\x92A\x82\x02\x127\n" +
	"\x1dOpenID AuthZen Access Service\"\x00*\v\n" +
	"\tApache v22\a1.0.0-3*\x02\x01\x022\x10application/json:\x10application/jsonR\x14\n" +
	"\x03400\x12\r\n" +
	"\vBad RequestR\x15\n" +
	"\x03401\x12\x0e\n" +
	"\fUnauthorizedR\x12\n" +
	"\x03403\x12\v\n" +
	"\tForbiddenR\x17\n" +
	"\x03500\x12\x10\n" +
	"\x0eInternal errorrE\n" +
	" Authorization API 1.0 - draft 03\x12!https://openid.github.io/authzen/\n" +
	"\x15com.authzen.access.v1B\vAccessProtoP\x01Z#github.com/authzen/access/v1;access\xa2\x02\x03AAX\xaa\x02\x11Authzen.Access.V1\xca\x02\x11Authzen\\Access\\V1\xe2\x02\x1dAuthzen\\Access\\V1\\GPBMetadata\xea\x02\x13Authzen::Access::V1b\x06proto3"

var (
	file_access_v1_access_proto_rawDescOnce sync.Once
	file_access_v1_access_proto_rawDescData []byte
)

func file_access_v1_access_proto_rawDescGZIP() []byte {
	file_access_v1_access_proto_rawDescOnce.Do(func() {
		file_access_v1_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_access_v1_access_proto_rawDesc), len(file_access_v1_access_proto_rawDesc)))
	})
	return file_access_v1_access_proto_rawDescData
}

var file_access_v1_access_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_access_v1_access_proto_goTypes = []any{
	(*EvaluationRequest)(nil),      // 0: authzen.access.v1.EvaluationRequest
	(*EvaluationResponse)(nil),     // 1: authzen.access.v1.EvaluationResponse
	(*EvaluationsRequest)(nil),     // 2: authzen.access.v1.EvaluationsRequest
	(*EvaluationsResponse)(nil),    // 3: authzen.access.v1.EvaluationsResponse
	(*SubjectSearchRequest)(nil),   // 4: authzen.access.v1.SubjectSearchRequest
	(*SubjectSearchResponse)(nil),  // 5: authzen.access.v1.SubjectSearchResponse
	(*ResourceSearchRequest)(nil),  // 6: authzen.access.v1.ResourceSearchRequest
	(*ResourceSearchResponse)(nil), // 7: authzen.access.v1.ResourceSearchResponse
	(*ActionSearchRequest)(nil),    // 8: authzen.access.v1.ActionSearchRequest
	(*ActionSearchResponse)(nil),   // 9: authzen.access.v1.ActionSearchResponse
	(*Subject)(nil),                // 10: authzen.access.v1.Subject
	(*Action)(nil),                 // 11: authzen.access.v1.Action
	(*Resource)(nil),               // 12: authzen.access.v1.Resource
	(*Page)(nil),                   // 13: authzen.access.v1.Page
	(*structpb.Struct)(nil),        // 14: google.protobuf.Struct
}
var file_access_v1_access_proto_depIdxs = []int32{
	10, // 0: authzen.access.v1.EvaluationRequest.subject:type_name -> authzen.access.v1.Subject
	11, // 1: authzen.access.v1.EvaluationRequest.action:type_name -> authzen.access.v1.Action
	12, // 2: authzen.access.v1.EvaluationRequest.resource:type_name -> authzen.access.v1.Resource
	14, // 3: authzen.access.v1.EvaluationRequest.context:type_name -> google.protobuf.Struct
	14, // 4: authzen.access.v1.EvaluationResponse.context:type_name -> google.protobuf.Struct
	10, // 5: authzen.access.v1.EvaluationsRequest.subject:type_name -> authzen.access.v1.Subject
	11, // 6: authzen.access.v1.EvaluationsRequest.action:type_name -> authzen.access.v1.Action
	12, // 7: authzen.access.v1.EvaluationsRequest.resource:type_name -> authzen.access.v1.Resource
	14, // 8: authzen.access.v1.EvaluationsRequest.context:type_name -> google.protobuf.Struct
	0,  // 9: authzen.access.v1.EvaluationsRequest.evaluations:type_name -> authzen.access.v1.EvaluationRequest
	14, // 10: authzen.access.v1.EvaluationsRequest.options:type_name -> google.protobuf.Struct
	1,  // 11: authzen.access.v1.EvaluationsResponse.evaluations:type_name -> authzen.access.v1.EvaluationResponse
	10, // 12: authzen.access.v1.SubjectSearchRequest.subject:type_name -> authzen.access.v1.Subject
	11, // 13: authzen.access.v1.SubjectSearchRequest.action:type_name -> authzen.access.v1.Action
	12, // 14: authzen.access.v1.SubjectSearchRequest.resource:type_name -> authzen.access.v1.Resource
	14, // 15: authzen.access.v1.SubjectSearchRequest.context:type_name -> google.protobuf.Struct
	13, // 16: authzen.access.v1.SubjectSearchRequest.page:type_name -> authzen.access.v1.Page
	10, // 17: authzen.access.v1.SubjectSearchResponse.results:type_name -> authzen.access.v1.Subject
	13, // 18: authzen.access.v1.SubjectSearchResponse.page:type_name -> authzen.access.v1.Page
	10, // 19: authzen.access.v1.ResourceSearchRequest.subject:type_name -> authzen.access.v1.Subject
	11, // 20: authzen.access.v1.ResourceSearchRequest.action:type_name -> authzen.access.v1.Action
	12, // 21: authzen.access.v1.ResourceSearchRequest.resource:type_name -> authzen.access.v1.Resource
	14, // 22: authzen.access.v1.ResourceSearchRequest.context:type_name -> google.protobuf.Struct
	13, // 23: authzen.access.v1.ResourceSearchRequest.page:type_name -> authzen.access.v1.Page
	12, // 24: authzen.access.v1.ResourceSearchResponse.results:type_name -> authzen.access.v1.Resource
	13, // 25: authzen.access.v1.ResourceSearchResponse.page:type_name -> authzen.access.v1.Page
	10, // 26: authzen.access.v1.ActionSearchRequest.subject:type_name -> authzen.access.v1.Subject
	11, // 27: authzen.access.v1.ActionSearchRequest.action:type_name -> authzen.access.v1.Action
	12, // 28: authzen.access.v1.ActionSearchRequest.resource:type_name -> authzen.access.v1.Resource
	14, // 29: authzen.access.v1.ActionSearchRequest.context:type_name -> google.protobuf.Struct
	13, // 30: authzen.access.v1.ActionSearchRequest.page:type_name -> authzen.access.v1.Page
	11, // 31: authzen.access.v1.ActionSearchResponse.results:type_name -> authzen.access.v1.Action
	13, // 32: authzen.access.v1.ActionSearchResponse.page:type_name -> authzen.access.v1.Page
	14, // 33: authzen.access.v1.Subject.properties:type_name -> google.protobuf.Struct
	14, // 34: authzen.access.v1.Action.properties:type_name -> google.protobuf.Struct
	14, // 35: authzen.access.v1.Resource.properties:type_name -> google.protobuf.Struct
	0,  // 36: authzen.access.v1.Access.Evaluation:input_type -> authzen.access.v1.EvaluationRequest
	2,  // 37: authzen.access.v1.Access.Evaluations:input_type -> authzen.access.v1.EvaluationsRequest
	4,  // 38: authzen.access.v1.Access.SubjectSearch:input_type -> authzen.access.v1.SubjectSearchRequest
	6,  // 39: authzen.access.v1.Access.ResourceSearch:input_type -> authzen.access.v1.ResourceSearchRequest
	8,  // 40: authzen.access.v1.Access.ActionSearch:input_type -> authzen.access.v1.ActionSearchRequest
	1,  // 41: authzen.access.v1.Access.Evaluation:output_type -> authzen.access.v1.EvaluationResponse
	3,  // 42: authzen.access.v1.Access.Evaluations:output_type -> authzen.access.v1.EvaluationsResponse
	5,  // 43: authzen.access.v1.Access.SubjectSearch:output_type -> authzen.access.v1.SubjectSearchResponse
	7,  // 44: authzen.access.v1.Access.ResourceSearch:output_type -> authzen.access.v1.ResourceSearchResponse
	9,  // 45: authzen.access.v1.Access.ActionSearch:output_type -> authzen.access.v1.ActionSearchResponse
	41, // [41:46] is the sub-list for method output_type
	36, // [36:41] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_access_v1_access_proto_init() }
func file_access_v1_access_proto_init() {
	if File_access_v1_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_access_v1_access_proto_rawDesc), len(file_access_v1_access_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_access_v1_access_proto_goTypes,
		DependencyIndexes: file_access_v1_access_proto_depIdxs,
		MessageInfos:      file_access_v1_access_proto_msgTypes,
	}.Build()
	File_access_v1_access_proto = out.File
	file_access_v1_access_proto_goTypes = nil
	file_access_v1_access_proto_depIdxs = nil
}
